name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "wine-mirror/wine"
        ref: "wine-10.8"
    - name: Cache Homebrew packages
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/Cellar
          /opt/homebrew/lib
          /opt/homebrew/include
        key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Brewfile') }}
        restore-keys: |
          homebrew-${{ runner.os }}-${{ runner.arch }}-
    - run: |
        brew install llvm
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
