name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout wine-arm64ec repo (for actions)
      uses: actions/checkout@v4
      with:
        path: wine-arm64ec-repo
    - uses: actions/checkout@v4
      with:
        repository: "wine-mirror/wine"
        ref: "wine-10.8"
        path: wine-source
    - name: Create Brewfile
      run: |
        cat > Brewfile << EOF
        brew "llvm"
        brew "bison"
        brew "molten-vk"
        brew "ccache"
        EOF
    - name: Cache Homebrew packages
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/Cellar
          /opt/homebrew/lib
          /opt/homebrew/include
          /opt/homebrew/bin
          /opt/homebrew/share
        key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Brewfile') }}
        restore-keys: |
          homebrew-${{ runner.os }}-${{ runner.arch }}-
    - run: |
        brew install llvm bison
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
        echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
    - name: Setup llvm-mingw
      uses: ./wine-arm64ec-repo/.github/actions/setup-llvm-mingw
    - name: configure
      working-directory: wine-source
      run: ./configure
    - name: make
      working-directory: wine-source
      run: make
    - name: make check
      working-directory: wine-source
      run: make check
    - name: make distcheck
      working-directory: wine-source
      run: make distcheck
